theme: jekyll-theme-minimal
title: ADA Go woke get Broke
description: A test from the GOAT Maurice Gauché
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Test
    url: test
